"""initial schema — tribunais, processos, movimentos, documentos, partes, advogados

Revision ID: 47c8ac3afea3
Revises: 
Create Date: 2026-04-29 16:16:36.653884
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '47c8ac3afea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advogados_cadastrados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('oab_numero', sa.String(length=20), nullable=False),
    sa.Column('oab_uf', sa.String(length=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('tribunais',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sistema', sa.String(length=20), nullable=False),
    sa.Column('wsdl_url', sa.String(length=500), nullable=False),
    sa.Column('mni_version', sa.String(length=10), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_cnj', sa.String(length=25), nullable=False),
    sa.Column('tribunal_id', sa.String(length=20), nullable=False),
    sa.Column('classe', sa.String(length=200), nullable=True),
    sa.Column('assunto', sa.Text(), nullable=True),
    sa.Column('valor_causa', sa.Float(), nullable=True),
    sa.Column('orgao_julgador', sa.String(length=300), nullable=True),
    sa.Column('data_ajuizamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grau', sa.String(length=20), nullable=True),
    sa.Column('dados_extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tribunal_id'], ['tribunais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processos_numero_cnj'), 'processos', ['numero_cnj'], unique=True)
    op.create_table('documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processo_id', sa.UUID(), nullable=False),
    sa.Column('id_documento_tribunal', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processo_id', sa.UUID(), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('codigo_nacional', sa.Integer(), nullable=True),
    sa.Column('complemento', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id_movimento', sa.String(length=100), nullable=True),
    sa.Column('categoria_semantica', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimentos_dedup', 'movimentos', ['processo_id', 'data_hora', 'codigo_nacional', 'id_movimento'], unique=True)
    op.create_table('partes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('processo_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('advogados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partes')
    op.drop_index('ix_movimentos_dedup', table_name='movimentos')
    op.drop_table('movimentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_processos_numero_cnj'), table_name='processos')
    op.drop_table('processos')
    op.drop_table('tribunais')
    op.drop_table('advogados_cadastrados')
    # ### end Alembic commands ###
